### ISSUE TITLE
Removal of nightly dependency

### ISSUE THREAD

**Issue by vados-cosmonic** [bytecodealliance/WASI-Virt#31]
## Context

As discussed in https://github.com/bytecodealliance/WASI-Virt/pull/21, it may be possible to find a way to remove the dependency on Rust Nightly. 

This issue represents that effort and any experimentation that may be necessary, with at least a few methods already discussed:

## Proposal

There were a couple of options presented:

- Removing `-Zoom=panic` (likely to cause an increase in code size)
- Avoiding using custom flags in Cargo.toml

While not previously discussed, it *seems* to be using a `build.rs` script ([emitting `cargo:rustc-flags=FLAGS`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-flags)), since [`profile.rustflags`](https://doc.rust-lang.org/cargo/reference/unstable.html?highlight=rustflags#profile-rustflags-option) are passed to the compiler (it doesn't look like there's any way to emit anything to pass to the linker on a rust lib target.

**Comment by guybedford** [comment]
This was landed in https://github.com/bytecodealliance/WASI-Virt/pull/62.
