### ISSUE TITLE
Failure on proc_exit()

### ISSUE THREAD

**Issue by leon-thomm** [bytecodealliance/WASI-Virt#38]
**edit**: I was able to reduce the issue to `proc_exit`, see edit history for the original post.

Consider the minimal WASM core module:

```wasm
(module
  (import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))

  (memory 1)
  (export "memory" (memory 0))

  (func $main (export "_start")
    (call $proc_exit
      (i32.const 0)
    )
  )
)
```
- successfully runs on wasmtime
- componetizing with `wasm-tools component new --adapt <path/to/preview-1-adapter>.command.wasm` yields a component which also runs successfully
- virtualizing the component with `--allow-all` proceeds, but running the virtualized component gives
```
Error: failed to run main module `wasi-min-test-comp-virt.wasm`

Caused by:
    0: failed to invoke `run` function
    1: error while executing at wasm backtrace:
           0: 0x109b6 - <unknown>!<wasm function 199>
           1:  0x1d5 - <unknown>!<wasm function 9>
           2: 0x1057 - wit-component:adapter:wasi_snapshot_preview1!wasi_snapshot_preview1::bindings::wasi::cli::exit::exit::hf9e2fc729a0e81cd
           3:  0xc4d - wit-component:adapter:wasi_snapshot_preview1!proc_exit
           4: 0x1855 - wit-component:shim!adapt-wasi_snapshot_preview1-proc_exit
           5:  0x28b - <unknown>!<wasm function 1>
           6:  0x4e7 - wit-component:adapter:wasi_snapshot_preview1!wasi:cli/run@0.2.0-rc-2023-10-18#run
    2: wasm trap: wasm `unreachable` instruction executed
```

- wasmtime 14.0.4
- wasm-tools 1.0.54
- wasi-virt 0.1.0

**Comment by leon-thomm** [comment]
The above succeeds when specifically passing `--allow-exit`. Also, running with `--allow-clocks` crashes WASI-Virt

```
assertion failed: prev.is_none() ||\n    (matches!(id, ComponentAnyTypeId :: Resource(_)) && prev == Some(value))
```

**Comment by guybedford** [comment]
I think the clocks issue here is actually a separate bug. Now that WASI-Virt is on the latest bindgen would be great to know if thats still an issue or if you can share a replication further in a new issue.
