### ISSUE TITLE
wasi-virt throws error in wasm-compose

### ISSUE THREAD

**Issue by thesuhas** [bytecodealliance/WASI-Virt#56]
Hi,

I'm trying to use `wasi-virt` with a micro service that I have written in rust. I want to give it a pre-opened file directory so that I can read a json file.
I am using this command: ` wasi-virt --debug --stderr=allow composed-cinema.wasm --preopen microservices/cinema-1/users=/data --allow-http -o virt-cinema.wasm`
And I get the following error:
<img width="1144" alt="image" src="https://github.com/bytecodealliance/WASI-Virt/assets/54014218/f9acd461-4ed7-4fd8-9d06-95e90f4e40e5">

It seems to be an error in `wasm-compose`. For some additional context, the micro service was composed by using the `http@3.0 draft` from [here](https://github.com/dicej/isyswasfa).

**Comment by guybedford** [comment]
Thanks for informing about this case, if it's a wasm-tools compose issue, then it should be posted as a bug to the wasm-tools repo at https://github.com/bytecodealliance/wasm-tools. Let me know if you're able to share it there, otherwise I can cross-post as well.
